name: Build status

on:
  push:
      branches: 
        - main
  pull_request:
    branches: 
      - main

jobs:

  ubuntu-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run npm test
      env:
        CI: true
      run: |
        npm ci
        npm run build --if-present
        npm test -- --watch=false
