ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Suppression des utilisateurs
DROP USER GLPI_CERGY_ADMIN1 CASCADE;
DROP USER GLPI_CERGY_DEV1 CASCADE;
DROP USER GLPI_CERGY_ANALYST1 CASCADE;
DROP USER GLPI_CERGY_OBSERVER1 CASCADE;

COMMIT;
exit;
