ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Création de l'utilisateur admin
CREATE USER GLPI_CERGY_ADMIN1 IDENTIFIED BY your_password;
GRANT GLPI_CERGY_ADMIN TO GLPI_CERGY_ADMIN1;

-- Création de l'utilisateur dev
CREATE USER GLPI_CERGY_DEV1 IDENTIFIED BY your_password;
GRANT GLPI_CERGY_DEV TO GLPI_CERGY_DEV1;

-- Création de l'utilisateur analyst
CREATE USER GLPI_CERGY_ANALYST1 IDENTIFIED BY your_password;
GRANT GLPI_CERGY_ANALYST TO GLPI_CERGY_ANALYST1;

-- Création de l'utilisateur observer
CREATE USER GLPI_CERGY_OBSERVER1 IDENTIFIED BY your_password;
GRANT GLPI_CERGY_OBSERVER TO GLPI_CERGY_OBSERVER1;


COMMIT;
exit;
