ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
SET SERVEROUTPUT OFF;

--Creation TABLESPACES et SCHEMA GLPI_PAU
CREATE TABLESPACE GLPI_PAU_TABSPACE
datafile 'C:\TAD\GLPI_DB_PAU\GLPI_PAU_TABSPACE.dat'
SIZE 100M AUTOEXTEND ON;


CREATE TEMPORARY TABLESPACE GLPI_PAU_TABSPACE_TEMP
tempfile 'C:\TAD\GLPI_DB_PAU\GLPI_PAU_TABSPACE_TEMP.dat'
SIZE 50M AUTOEXTEND ON;

CREATE USER GLPI_PAU 
IDENTIFIED BY GLPI_PAU_PASSWORD
DEFAULT TABLESPACE GLPI_PAU_TABSPACE
TEMPORARY TABLESPACE GLPI_PAU_TABSPACE_TEMP;

GRANT CONNECT, CREATE SESSION TO GLPI_PAU;
GRANT DBA TO GLPI_PAU;

--Creation TABLESPACES et SCHEMA GLPI_CERGY
CREATE TABLESPACE GLPI_CERGY_TABSPACE
datafile 'C:\TAD\GLPI_DB_CERGY\GLPI_CERGY_TABSPACE.dat'
SIZE 100M AUTOEXTEND ON;

CREATE TEMPORARY TABLESPACE GLPI_CERGY_TABSPACE_TEMP
tempfile 'C:\TAD\GLPI_DB_CERGY\GLPI_CERGY_TABSPACE_TEMP.dat'
SIZE 50M AUTOEXTEND ON;

CREATE USER GLPI_CERGY 
IDENTIFIED BY GLPI_CERGY_PASSWORD
DEFAULT TABLESPACE GLPI_CERGY_TABSPACE
TEMPORARY TABLESPACE GLPI_CERGY_TABSPACE_TEMP;

GRANT CONNECT, CREATE SESSION TO GLPI_CERGY;
GRANT DBA TO GLPI_CERGY;


-- -- Création du tablespace et du tablespace temporaire pour GLPI_OBSERVER
-- CREATE TABLESPACE GLPI_OBSERVER_TS DATAFILE 'C:\TAD\GLPI_ROLES\GLPI_OBSERVER_TS.dat' SIZE 100M AUTOEXTEND ON;
-- CREATE TEMPORARY TABLESPACE GLPI_OBSERVER_TEMP_TS TEMPFILE 'C:\TAD\GLPI_ROLES\GLPI_OBSERVER_TEMP_TS.dbf' SIZE 50M AUTOEXTEND ON;

-- -- Création du tablespace et du tablespace temporaire pour GLPI_ANALYST
-- CREATE TABLESPACE GLPI_ANALYST_TS DATAFILE 'C:\TAD\GLPI_ROLES\GLPI_ANALYST_TS.dat' SIZE 100M AUTOEXTEND ON;
-- CREATE TEMPORARY TABLESPACE GLPI_ANALYST_TEMP_TS TEMPFILE 'C:\TAD\GLPI_ROLES\GLPI_ANALYST_TEMP_TS.dbf' SIZE 50M AUTOEXTEND ON;

-- -- Création du tablespace et du tablespace temporaire pour GLPI_DEV
-- CREATE TABLESPACE GLPI_DEV_TS DATAFILE 'C:\TAD\GLPI_ROLES\GLPI_DEV_TS.dat' SIZE 100M AUTOEXTEND ON;
-- CREATE TEMPORARY TABLESPACE GLPI_DEV_TEMP_TS TEMPFILE 'C:\TAD\GLPI_ROLES\GLPI_DEV_TEMP_TS.dbf' SIZE 50M AUTOEXTEND ON;

-- -- Création du tablespace et du tablespace temporaire pour GLPI_ADMIN
-- CREATE TABLESPACE GLPI_ADMIN_TS DATAFILE 'C:\TAD\GLPI_ROLES\GLPI_ADMIN_TS.dat' SIZE 100M AUTOEXTEND ON;
-- CREATE TEMPORARY TABLESPACE GLPI_ADMIN_TEMP_TS TEMPFILE 'C:\TAD\GLPI_ROLES\GLPI_ADMIN_TEMP_TS.dbf' SIZE 50M AUTOEXTEND ON;


COMMIT;
exit;
