ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;


-- Supprimer les rôles
DROP ROLE GLPI_CERGY_ADMIN;
DROP ROLE GLPI_CERGY_DEV;
DROP ROLE GLPI_CERGY_ANALYST;
DROP ROLE GLPI_CERGY_OBSERVER;

-- Supprimer les rôles
DROP ROLE GLPI_PAU_ADMIN;
DROP ROLE GLPI_PAU_DEV;
DROP ROLE GLPI_PAU_ANALYST;
DROP ROLE GLPI_PAU_OBSERVER;

DROP ROLE GLPI_FULL_ADMIN;


COMMIT;
exit;
