-- vue globale pour cergy
CREATE VIEW GLPI_CERGY.FULL_GLOBAL_TICKET
AS
SELECT * FROM GLPI_CERGY.GLOBAL_TICKET
UNION 
SELECT * FROM GLPI_PAU.GLOBAL_TICKET@LK_GLPI_PAU;

GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_CERGY.FULL_GLOBAL_TICKET TO GLPI_CERGY_DEV

-- vue globale pour pau
CREATE VIEW GLPI_PAU.FULL_GLOBAL_TICKET
AS
SELECT * FROM GLPI_PAU.GLOBAL_TICKET
UNION 
SELECT * FROM GLPI_CERGY.GLOBAL_TICKET@LK_GLPI_CERGY;

GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_PAU.FULL_GLOBAL_TICKET TO GLPI_PAU_DEV

COMMIT;
exit;
