-- Appels des fonctions
EXECUTE GLPI_PAU.REFRESH_MATERIALIZED_VIEW('GLPI_PAU.GLOBAL_TICKET');
EXECUTE GLPI_PAU.SET_TICKET_STATUS(1, 'To do');
EXECUTE GLPI_PAU.SOLVE_TICKET(1, 'Resolu avec la procedure');
EXECUTE GLPI_PAU.CLOSE_TICKET(1);
EXECUTE GLPI_PAU.ASSIGN_TICKET_TO_USER(3, 1);
EXECUTE GLPI_PAU.ADD_REMOVE_OBSERVER_OF_TICKET(1 ,1);

--TEST DE GET_TICKET
CREATE TABLE TEMP_TABLE AS
SELECT * FROM GLPI_PAU.GLOBAL_Ticket WHERE 1 = 0; 
/
DECLARE
    v_ticket GLPI_PAU.GLOBAL_Ticket%ROWTYPE;
BEGIN
    v_ticket := GLPI_PAU.GET_TICKET(1);
    INSERT INTO TEMP_TABLE VALUES v_ticket;
END;
/
SET SERVEROUTPUT ON;
/
SELECT * FROM TEMP_TABLE;
/
SET SERVEROUTPUT OFF;
/

--TEST DE GLPI_PAU.GET_USER_TICKETS
CREATE TABLE TEMP_TABLE2 (ticket_id INT);
DECLARE
    ticket_id_list SYS.ODCINUMBERLIST;
    i INT;
BEGIN
    ticket_id_list := GLPI_PAU.GET_USER_TICKETS(1);
    
    FOR i IN 1..ticket_id_list.COUNT LOOP
        INSERT INTO TEMP_TABLE2 VALUES (ticket_id_list(i));
    END LOOP;
END;
/
SET SERVEROUTPUT ON;
/
SELECT * FROM TEMP_TABLE2;
/
SET SERVEROUTPUT OFF;
/

/

--TEST DE GLPI_PAU.GET_TICKET_COMMENTS
CREATE TABLE TEMP_TABLE3 (comment_id INT);
DECLARE
    comment_id_list SYS.ODCINUMBERLIST;
    i INT;
BEGIN
    comment_id_list := GLPI_PAU.GET_TICKET_COMMENTS(2);
    
    FOR i IN 1..comment_id_list.COUNT LOOP
        INSERT INTO TEMP_TABLE3 VALUES (comment_id_list(i));
    END LOOP;
END;
/
SET SERVEROUTPUT ON;
/
SELECT * FROM TEMP_TABLE3;
/
SET SERVEROUTPUT OFF;
/

/

DROP TABLE TEMP_TABLE;
DROP TABLE TEMP_TABLE2;
DROP TABLE TEMP_TABLE3;


COMMIT;
EXIT;
