ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Suppression des utilisateurs
DROP USER GLPI_PAU_ADMIN1 CASCADE;
DROP USER GLPI_PAU_DEV1 CASCADE;
DROP USER GLPI_PAU_ANALYST1 CASCADE;
DROP USER GLPI_PAU_OBSERVER1 CASCADE;

COMMIT;
exit;
